# Generated by Django 3.1.8 on 2021-04-19 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210411_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='measurement',
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category'),
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
